In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,5,101)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05,
       1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 , 1.55, 1.6 ,
       1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  , 2.05, 2.1 , 2.15,
       2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 , 2.55, 2.6 , 2.65, 2.7 ,
       2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  , 3.05, 3.1 , 3.15, 3.2 , 3.25,
       3.3 , 3.35, 3.4 , 3.45, 3.5 , 3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 ,
       3.85, 3.9 , 3.95, 4.  , 4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35,
       4.4 , 4.45, 4.5 , 4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 ,
       4.95, 5.  ])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.39717376, 0.6221317 , 0.76991163, 0.94155075, 0.17622326])

In [27]:
np.random.rand(5,5)

array([[0.15225135, 0.93809335, 0.5962907 , 0.75385728, 0.94860846],
       [0.69627375, 0.03100516, 0.22862736, 0.27491875, 0.80077416],
       [0.83961779, 0.07686104, 0.05983407, 0.02980487, 0.37166969],
       [0.30663644, 0.820371  , 0.49385856, 0.2479609 , 0.73454553],
       [0.95123871, 0.39476948, 0.17183362, 0.41083122, 0.85171003]])

In [23]:
np.random.randn(5)

array([ 1.21539868,  0.60508383,  0.26129217, -1.43964637, -0.52796927])

In [26]:
np.random.randint(1,100,10)

array([58, 33, 40, 67, 78, 77, 65, 67, 19, 84])

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr = np.random.randint(0,50,10)

In [31]:
ranarr

array([34, 23, 43,  5, 18,  5, 37, 41, 35, 35])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr.max()

43

In [36]:
ranarr.min()

5

In [37]:
ranarr

array([34, 23, 43,  5, 18,  5, 37, 41, 35, 35])

In [38]:
ranarr.argmax()

2

In [39]:
ranarr.argmin()

3

In [40]:
arr.shape

(25,)

In [41]:
arr = arr.reshape(5,5)

In [42]:
arr.shape

(5, 5)

In [43]:
arr.dtype

dtype('int32')

In [44]:
from numpy.random import randint

In [47]:
randint(2,10,5)

array([7, 2, 4, 7, 6])